# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170523_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dispensary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='distributer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='grower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='medical',
            field=models.BooleanField(default=False),
        ),
    ]
