# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170527_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='medical',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='verified_dispensary',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='verified_distributer',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
