# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170729_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='medical',
            new_name='api_hits',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='user_uuid',
            new_name='authtoken',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='grower',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='verified_dispensary',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='verified_distributer',
        ),
    ]
